appName: myhelmapp

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: cloud2796/webapp
  tag: 34

service:
  type: ClusterIP
  port: 80
